# Generated by Django 6.0 on 2025-12-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeApp',
        ),
    ]
